name: crud_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.2
  file_picker: ^8.1.7  # <-- GANTI KE VERSI INI
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.5
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  